# version: "3.9"
services:
  api:
    build: ./
    container_name: policybot-api
    environment:
      - PYTHONUNBUFFERED=1
      - EMBED_MODEL=BAAI/bge-small-en-v1.5
      - CHROMA_DIR=/data/chroma
      - ALLOW_ORIGIN=http://localhost:5173
      - API_AUTH_TOKEN=dev-token-123
    volumes:
      - chroma_data:/data/chroma
      - ./trial_project:/app
    ports:
      - "8000:8000"
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: "http://localhost:8000"
    container_name: policybot-web
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  chroma_data:

# mytoken slack bot=xapp-1-A09ELM93KED-9469003174471-30c639b808f31581765a66ff9663cac96c24c992e46fbcd691ade54b33a232a2
# Bot User OAuth Token=xoxb-9487410091860-9483575441318-znZwbMZlum7Pxw8XWfW9BLHu